### ISSUE TITLE
[QUESTION] Headers generated inside android app

### ISSUE THREAD

**Issue by caiquejjx** [defnotcat/shape-unpacker#1]
Hey, I'm currently reverse engineering a app that uses Shape and I even got to the point where I'm able to generate 6 headers (the ones generated by the js script) but apparently the only one that matters is the header that ends with an "e" (at least for this app) and according to the tests I made this header is generated inside the android application, outside the js script, using your tool I was able to get some more code than with a decompiler but I still haven't found where and how it is generated, do you have any idea?

**Comment by defnotcat** [comment]
Hello!

Indeed the only header that actually matters on mobile is `-e` afaik. The header contains a bunch of your device's sensors data as a JSON string that's then compressed and encrypted. Almost all the fields in that JSON as well as the compression and encryption are done by Java code that you can find in the `internal.dex` file provided by the unpacker. Don't remember in which classes exactly.

Here's a tip: All the JSON fields and their values are added through `java.util.HashMap.put(K, V)` at some point in the code, just hook that with Frida and you should eventually find what you're looking for. 

Hope that helped. Good luck :)

**Comment by caiquejjx** [comment]
That's really helpful, gonna try those out.
Thank you!

**Comment by mightatnight** [comment]
@caiquejjx Hey! Can i have your discord?
My discord is vasylchuk
