### ISSUE TITLE
Function to generate shape encoded

### ISSUE THREAD

**Issue by giovanniguaceroni** [defnotcat/shape-unpacker#3]
Hey, I'm currently reverse engineering a app that uses Shape and I even got to the point where the payload was encrypted. Using Json like i saw in your answer in past issues. But i want to know now, where is the function to encrypt the data. I tried hook so many methods (100+) but most of them have a name (getHeader(), getMethod(), getBody(), AGRequest()) and i not was able to track which these methods generate final script. I got hooking StringBuilder(append) method, i can saw the payload but inside a lot of strings into the app. So i want to know what can i do to see what's function returns script encoded. Thanks !!

**Comment by giovanniguaceroni** [comment]
If i get in touch in discord or some method i will really appreciate. Thanks for your job, defnotcat!!

**Comment by defnotcat** [comment]
Hey mate! 

The encryption happens in the internal .DEX file that's dynamically loaded at runtime. This very repository should help you unpack it, all you need to do is find the name and package of a class that's contained in it, and put that in the `TestInternalClass` const.

In the `KernelPayloadInstance` class, try to look for a method that calls `hashMap.put` a bunch of times (with very weird arguments), then see where it's being invoked, where it leads, etc... That should lead you to the encryption.

Hope that helps, good luck! Please leave your Discord username here if you need further assistance.

**Comment by giovanniguaceroni** [comment]
Thanks mate !! You are awesome ! , my discord is FORGET#1613 please add if u can.

**Comment by charlie-maxrewards** [comment]
Also have a couple questions on this, add me on discord if possible ->  borisjohnson691#9384. Thanks for the tools!

**Comment by mightatnight** [comment]
@charlie-maxrewards  @giovanniguaceroni  Hey! Can i have your discord?
My discord is vasylchuk
