### ISSUE TITLE
How can I hook a class in InMemoryDexClassLoader?

### ISSUE THREAD

**Issue by asafe199** [defnotcat/shape-unpacker#4]
Hi there!

I saw the recently Issues and it was pretty helpful, in this [comment](https://github.com/defnotcat/shape-unpacker/issues/3#issuecomment-1503886081) you mentioned a class that create a bunch of parameters. 
I'm using Frida and I'm not able to hook the class always return ClassNotFound.

I tested with this [example](https://github.com/frida/frida/issues/1049) and didn't work
and also something like this:

```
Java.enumerateClassLoaders({
        onMatch: function(loader){
            Java.classFactory.loader = loader;
            var CLASS;
            try{
                CLASS = Java.use("com.apiguard3.internal.KernelPayloadInstance");
//              CLASS.method.implementation = function(){
//                  console.log("[+] Inside method");
//            }
            } catch(err){
               console.error(err)
            }
        },
        onComplete: function(){

        }
    }); 
```

Do you have an example of code using Frida hooking this class? i really appreciate it your help.

**Comment by defnotcat** [comment]
Hey there! 

You were definitely on the right path, you do need to explicitly tell Frida where to look (using `Java.classFactory.loader`), which you were doing correctly, but there's a better way of figuring out what class loader actually loaded the class, see:

```js
const target = "com.apiguard3.internal.KernelPayloadInstance";

Java.classFactory.loader = Java.enumerateMethods(`${target}!*`)[0].loader;

Java.use(target)["method"].implementation = function() {
   console.log("Hey from KernelPayloadInstance!")
}
```

Hope that helps. Good luck in your project :)

**Comment by asafe199** [comment]
Thanks man for your help!!

**Comment by mightatnight** [comment]
@asafe199 Hey! Can i have your discord?
My discord is vasylchuk
